services:
    web:
        build: .
        env_file: .env
        container_name: paas-api
        restart: always
        ports:
            - 4001:80
        volumes:
        - /var/www/paas/deployed_apps:/app/deployed_apps
        - /var/www/paas/deployed_apps_logs:/app/deployed_apps_logs
        - /var/www/paas/deployed_nginx_files:/app/deployed_nginx_files
        - /var/www/paas/database:/app/database
        - /var/www/paas/success-report:/app/success-report
        - /var/www/paas/destroy-report:/app/destroy-report
        - /var/www/paas/rebuild-report:/app/rebuild-report
        - /var/www/paas/logs:/app/subdomain_logs
        - /etc/supervisor/conf.d:/app/inotify-scripts
# networks:
#   default:
#     driver: host
