version: '3'
services:
    web:
        build: .
        env_file: .env
        container_name: paas-api
        restart: always
        ports:
            - 4001:80
        volumes:
        - /var/www/paas-api/deployed_apps:/app/deployed_apps
        - /var/www/paas-api/deployed_apps_logs:/app/deployed_apps_logs
        - /var/www/paas-api/deployed_nginx_files:/app/deployed_nginx_files
        - /var/www/paas-api/database:/app/database

# networks:
#   default:
#     driver: host