version: '3'
services:
    web:
        build: .
        env_file: .env
        container_name: paas-api
        restart: always
        ports:
            - 4001:80
        volumes:
        - ./deployed_apps:/app/deployed_apps
        - ./deployed_apps_logs:/app/deployed_apps_logs
        - ./deployed_nginx_files:/app/deployed_nginx_files
        - ./database:/app/database

networks:
  default:
    driver: bridge